// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// ユーザーテーブル
type User struct {
	ID        uuid.UUID      `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	CreatedAt time.Time      `json:"createdAt"`
	Updatedat time.Time      `json:"updatedat"`
}
